#! /usr/bin/env python3
# -*- coding: utf-8 -*-

# -----------------------------------------------------------------------------
# imports
# -----------------------------------------------------------------------------
import shlex
import argparse
from flask import Flask
import shutil
import subprocess
import time
import json
import psycopg2
import os
import getpass
import glob
import sys
from distutils.dir_util import copy_tree

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
LOPOCS_MODULE_DIR = os.path.join(SCRIPT_DIR, "..")
sys.path.append(LOPOCS_MODULE_DIR)

from lopocs.database import Session
from lopocs.conf import Config
from lopocs import greyhound
from lopocs import threedtiles
from lopocs import utils

# -----------------------------------------------------------------------------
# const
# -----------------------------------------------------------------------------
USER=getpass.getuser()
HOME=os.path.expanduser("~")

# -----------------------------------------------------------------------------
# classes
# -----------------------------------------------------------------------------
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

# -----------------------------------------------------------------------------
# functions
# -----------------------------------------------------------------------------
def header(msg):
    print()
    print("============================================================")
    print(msg)
    print("============================================================")
    print()

def logger(msg='', res=False, valid=True, resmsg=''):
    if not res:
        print(msg + "...: ", end='')
    else:
        if valid:
            if resmsg:
                print(resmsg)
            else:
                print(bcolors.OKGREEN + "OK" + bcolors.ENDC)
        else:
            print(bcolors.FAIL + "FAIL" + bcolors.ENDC)

    sys.stdout.flush()


def config_summary(args):

    header("LOPoCS configuration")
    print("General")
    print(" - files: {}".format(args.files))
    print(" - output directory: {}".format(os.path.abspath(args.outdir)))
    print(" - epsg code: EPSG:{}".format(args.epsg))
    print(" - force: {}".format(args.force))
    print()
    print("Postgres")
    print(" - host: {}".format(args.pg_host))
    print(" - database: {}".format(args.pg_db))
    print(" - port: {}".format(args.pg_port))
    print(" - table: {}".format(args.pg_table))
    print(" - user: {}".format(args.pg_user))
    print(" - password: {}".format(args.pg_pwd))
    print()
    print("PDAL")
    print(" - reader: {}".format(args.pdal_reader))
    print(" - patch size: {}".format(args.pdal_patchsize))
    print()
    print("Morton")
    print(" - grid size: {0}".format(args.morton_size))
    print()
    print("Hierarchy")
    print(" - lod max: {0}".format(args.lod_max))
    print()
    print("LOPoCS")
    print(" - cache directory: {}".format(os.path.abspath(args.lopocs_cachedir)))
    print()
    print("UWSGI")
    print(" - host: {}".format(args.uwsgi_host))
    print(" - port: {}".format(args.uwsgi_port))
    print(" - logfile: {}".format(args.uwsgi_log))
    print(" - virtualenv: {}".format(args.uwsgi_venv))
    print()
    print("Viewer(s)")
    print(" - PotreeViewer: {}".format(args.potreeviewer))

def search_cmd(cmd):
    logger(cmd)

    cdb = shutil.which(cmd)
    if not cdb:
        logger(res=True, resmsg="not found")
        sys.exit()
    else:
        logger(res=True, resmsg=cdb)

    return cdb


def search_lib(libpath, libname):
    logger(libname)

    if os.path.isfile(libpath):
        logger(res=True, resmsg=libpath)
    else:
        logger(res=True, resmsg="not found")
        sys.exit()


def run_cmd(cmd):
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)
    out, err = p.communicate()
    return out, err


def checkenv(args):
    env = {}

    # database
    cmd = "dropdb"
    env[cmd] = search_cmd(cmd)

    cmd = "createdb"
    env[cmd] = search_cmd(cmd)

    # pdal stuff
    cmd = "pdal"
    env[cmd] = search_cmd(cmd)

    cmd = "pdal-config"
    env[cmd] = search_cmd(cmd)

    out, err = run_cmd([env["pdal-config"], "--plugin-dir"])
    pdal_plugindir = str(out, 'utf-8').replace('\n', '')
    midoc = os.path.join(pdal_plugindir, "libpdal_plugin_filter_midoc.so")
    search_lib(midoc, "pdal plugin midoc filter")

    pgpointcloud_writer = os.path.join(pdal_plugindir, "libpdal_plugin_writer_pgpointcloud.so")
    search_lib(pgpointcloud_writer, "pdal plugin pgpointcloud writer")

    return env

def getfiles(args):
    logger("Search input file(s)")

    files = []
    pattern = args.files
    for filename in glob.glob(pattern):
        files.append(os.path.abspath(filename))

    if not files:
        logger(res=True, valid=False)
        print("No input files found.")
        sys.exit()
    else:
        logger(res=True, valid=True)

    return files

def clean(args):
    logger("Remove output directory")
    if os.path.exists(args.outdir):
        shutil.rmtree(args.outdir)
    logger(res=True, valid=True)

    logger("Drop database")
    out, err = run_cmd([env['dropdb'], '--if-exists', args.pg_db])
    logger(res=True, valid=True)

def init_outdir(args):
    logger("Initialize output directory")
    if not os.path.exists(args.outdir):
        os.makedirs(args.outdir)

    args.pdal_dir = os.path.join(args.outdir, "pdal")
    if not os.path.exists(args.pdal_dir):
        os.makedirs(args.pdal_dir)
    logger(res=True, valid=True)

    logger("Initialize cache directory")
    if not os.path.exists(args.lopocs_cachedir):
        os.makedirs(args.lopocs_cachedir)
    logger(res=True, valid=True)

def initdb(args, env):
    logger("Create the database")
    out, err = run_cmd(shlex.split('{} {} {} {} {}'.format(
      env['createdb'],
      '-p {}'.format(args.pg_port) if args.pg_port else '',
      '-U {}'.format(args.pg_user) if args.pg_user else '',
      '-h {}'.format(args.pg_host) if args.pg_host else '',
      args.pg_db
    )))
    if err:
        logger(res=True, valid=False)
        print(err)
        sys.exit()
    else:
        logger(res=True, valid=True)

    logger("Initialize connection with database")
    app.config['PG_USER'] = args.pg_user
    app.config['PG_HOST'] = args.pg_host
    app.config['PG_TABLE'] = args.pg_table
    app.config['PG_COLUMN'] = 'pa'
    app.config['PG_PASSWORD'] = args.pg_pwd
    app.config['PG_PORT'] = args.pg_port
    app.config['PG_NAME'] = args.pg_db
    app.config['LOGGER_NAME'] = 'scan'
    Session.init_app(app)
    logger(res=True, valid=True)

    logger("Load postgis extension")
    query = "create extension if not exists postgis;"
    try:
        Session.db.cursor().execute(query)
        logger(res=True, valid=True)
    except psycopg2.OperationalError as err:
        logger(res=True, valid=False)
        print(err)
        sys.exit()

    logger("Load pointcloud extension")
    query = "create extension if not exists pointcloud;"
    try:
        Session.db.cursor().execute(query)
        logger(res=True, valid=True)
    except psycopg2.OperationalError as err:
        logger(res=True, valid=False)
        print(err)
        sys.exit()

    logger("Load pointcloud_postgis extension")
    query = "create extension if not exists pointcloud_postgis;"
    try:
        Session.db.cursor().execute(query)
        logger(res=True, valid=True)
    except psycopg2.OperationalError as err:
        logger(res=True, valid=False)
        print(err)
        sys.exit()

    logger("Load morton extension")
    query = "create extension if not exists morton;"
    try:
        Session.db.cursor().execute(query)
        logger(res=True, valid=True)
    except psycopg2.OperationalError as err:
        logger(res=True, valid=False)
        print(err)
        sys.exit()

    return Session.db.cursor()

def pdal_reader_las(epsg, filename):
    json = ('{{\n'
            '"type":"readers.las",\n'
            '"filename":"{0}",\n'
            '"spatialreference":"EPSG:{1}"\n'
            '}}\n').format(filename, epsg)
    return json

def pdal_reader_e57(filename):
    json = ('{{\n'
            '"type":"readers.e57",\n'
            '"filename":"{0}"\n'
            '}}\n').format(filename)
    return json

def pdal_pipeline(files, args, env):
    logger("Build PDAL pipelines")
    pipelines = []
    for f in files:
        basename = os.path.splitext(os.path.basename(f))[0]
        json_path = os.path.join(args.pdal_dir,
                                 '{0}.pipeline'.format(basename))
        fh = open(json_path, 'w')

        if args.pdal_reader == 'e57':
            reader_pipe = pdal_reader_e57(f)
        elif args.pdal_reader == 'las':
            reader_pipe = pdal_reader_las(args.epsg, f)

        json = ('{{\n'
                '"pipeline":[\n'
                '{0}'
                ',\n'
                '{{\n'
                '"type":"filters.chipper",\n'
                '"capacity":{1}\n'
                '}},\n'
                '{{\n'
                '"type":"filters.midoc"\n'
                '}},\n'
                '{{\n'
                '"type":"writers.pgpointcloud",\n'
                '"connection":"dbname={2} port={5} user={6} password={7}",\n'
                '"table":"{3}",\n'
                '"compression":"lazperf",\n'
                '"srid":"{4}",\n'
                '"overwrite":"false"\n'
                '}}\n'
                ']\n'
                '}}\n'.format(
                  reader_pipe, args.pdal_patchsize,
                  args.pg_db, args.pg_table, args.epsg,
                  args.pg_port, args.pg_user, args.pg_pwd))

        fh.write(json)
        fh.close()

        pipelines.append(os.path.abspath(json_path))
    logger(res=True, valid=True)

    n = len(pipelines)
    for i in range(0, n):
        print("Run PDAL pipelines...: {0}/{1}".format(i, n), end='\r')
        sys.stdout.flush()
        pipe = pipelines[i]
        out, err = run_cmd([env['pdal'], 'pipeline', '-i', '{0}'.format(pipe)])
        if err:
            logger("Run PDAL pipelines")
            logger(res=True, valid=False)
            print(str(err, 'utf-8'))
            sys.exit()
    print("                                                     ", end='\r')
    logger("Run PDAL pipelines")
    logger(res=True, valid=True)

def getbbox():
    logger("Extract bounding box")
    fullbbox = Session.boundingbox()
    bbox = [fullbbox['xmin'], fullbbox['ymin'], fullbbox['zmin'],
            fullbbox['xmax'], fullbbox['ymax'], fullbbox['zmax']]
    logger(res=True, valid=True)

    return bbox

def emptyschema():
    schema = ('<?xml version="1.0" encoding="UTF-8"?>\n'
              '<pc:PointCloudSchema xmlns:pc="http://pointcloud.org/schemas/PC/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n'
              '<pc:dimension>\n'
              '<pc:position>1</pc:position>\n'
              '<pc:size>4</pc:size>\n'
              '<pc:description>X coordinate</pc:description>\n'
              '<pc:name>X</pc:name>\n'
              '<pc:interpretation>int32_t</pc:interpretation>\n'
              '<pc:scale>{0}</pc:scale>\n'
              '<pc:offset>{1}</pc:offset>\n'
              '<pc:active>true</pc:active>\n'
              '</pc:dimension>\n'
              '<pc:dimension>\n'
              '<pc:position>2</pc:position>\n'
              '<pc:size>4</pc:size>\n'
              '<pc:description>Y coordinate</pc:description>\n'
              '<pc:name>Y</pc:name>\n'
              '<pc:interpretation>int32_t</pc:interpretation>\n'
              '<pc:scale>{0}</pc:scale>\n'
              '<pc:offset>{2}</pc:offset>\n'
              '<pc:active>true</pc:active>\n'
              '</pc:dimension>\n'
              '<pc:dimension>\n'
              '<pc:position>3</pc:position>\n'
              '<pc:size>4</pc:size>\n'
              '<pc:description>Z coordinate</pc:description>\n'
              '<pc:name>Z</pc:name>\n'
              '<pc:interpretation>int32_t</pc:interpretation>\n'
              '<pc:scale>{0}</pc:scale>\n'
              '<pc:offset>{3}</pc:offset>\n'
              '<pc:active>true</pc:active>\n'
              '</pc:dimension>\n'
              '<pc:dimension>\n'
              '<pc:position>4</pc:position>\n'
              '<pc:size>2</pc:size>\n'
              '<pc:description>Representation of the pulse return magnitude</pc:description>\n'
              '<pc:name>Intensity</pc:name>\n'
              '<pc:interpretation>uint16_t</pc:interpretation>\n'
              '<pc:active>true</pc:active>\n'
              '</pc:dimension>\n'
              '<pc:dimension>\n'
              '<pc:position>5</pc:position>\n'
              '<pc:size>1</pc:size>\n'
              '<pc:description>ASPRS classification.  0 for no classification.</pc:description>\n'
              '<pc:name>Classification</pc:name>\n'
              '<pc:interpretation>uint8_t</pc:interpretation>\n'
              '<pc:active>true</pc:active>\n'
              '</pc:dimension>\n'
              '<pc:dimension>\n'
              '<pc:position>6</pc:position>\n'
              '<pc:size>2</pc:size>\n'
              '<pc:description>Red image channel value</pc:description>\n'
              '<pc:name>Red</pc:name>\n'
              '<pc:interpretation>uint16_t</pc:interpretation>\n'
              '<pc:active>true</pc:active>\n'
              '</pc:dimension>\n'
              '<pc:dimension>\n'
              '<pc:position>7</pc:position>\n'
              '<pc:size>2</pc:size>\n'
              '<pc:description>Green image channel value</pc:description>\n'
              '<pc:name>Green</pc:name>\n'
              '<pc:interpretation>uint16_t</pc:interpretation>\n'
              '<pc:active>true</pc:active>\n'
              '</pc:dimension>\n'
              '<pc:dimension>\n'
              '<pc:position>8</pc:position>\n'
              '<pc:size>2</pc:size>\n'
              '<pc:description>Blue image channel value</pc:description>\n'
              '<pc:name>Blue</pc:name>\n'
              '<pc:interpretation>uint16_t</pc:interpretation>\n'
              '<pc:active>true</pc:active>\n'
              '</pc:dimension>\n'
              '<pc:metadata>\n'
              '<Metadata name="compression" type="string"/>none</pc:metadata>\n'
              '<pc:orientation>point</pc:orientation>\n'
              '</pc:PointCloudSchema>\n')
    return schema

def potreeschema(args, bbox, cursor):
    print()

    xoffset = bbox[0] + (bbox[3]-bbox[0])/2
    yoffset = bbox[1] + (bbox[4]-bbox[1])/2
    zoffset = bbox[2] + (bbox[5]-bbox[2])/2

    xoffset = float("{0:.3f}".format(xoffset))
    yoffset = float("{0:.3f}".format(yoffset))
    zoffset = float("{0:.3f}".format(zoffset))

    logger("Insert Potree schema for scale=0.1")
    schema = emptyschema().format(0.1, xoffset, yoffset, zoffset)
    sql = ("INSERT INTO pointcloud_formats (pcid, srid, schema) VALUES (2, {0}, '{1}')"
           .format(args.epsg, schema))
    cursor.execute(sql)
    logger(res=True, valid=True)

    logger("Insert Potree schema for scale=0.01")
    schema = emptyschema().format(0.01, xoffset, yoffset, zoffset)
    sql = ("INSERT INTO pointcloud_formats (pcid, srid, schema) VALUES (3, {0}, '{1}')"
           .format(args.epsg, schema))
    cursor.execute(sql)
    logger(res=True, valid=True)

def morton_code(args, cursor):
    print()
    logger("Compute Morton code")

    sql = ("ALTER TABLE {0} add column morton bigint;".format(args.pg_table))
    cursor.execute(sql)

    sql = ("SELECT Morton_Update('{0}', 'pa', 'morton', {1}, TRUE)"
           .format(args.pg_table, args.morton_size))
    cursor.execute(sql)

    sql = ("CREATE index ON {0}(morton)".format(args.pg_table))
    cursor.execute(sql)

    logger(res=True, valid=True)

def create_patch_index(args, cursor):
    logger("Create geo index on patch")

    sql = (
      "create index if not exists {0}_pa_idx on {0} using gist(geometry(pa))"
      .format(args.pg_table)
    )
    cursor.execute(sql)

    logger(res=True, valid=True)

def hierarchy(app, args, bbox):
    print()

    logger("Generate a hierarchy file for Potree")

    # save hierarchy in file
    hierarchy = greyhound.build_hierarchy_from_pg_mp(args.lod_max, bbox, 0)
    path = os.path.join(args.lopocs_cachedir, 'potree.hcy')
    f = open(path, 'w')
    json.dump(hierarchy, f)
    f.close()
    logger(res=True, valid=True)

    logger("Paste the Potree hierarchy in LOPoCS cache directory")
    logger(res=True, valid=True)

    # logger("Generate a hierarchy file for Cesium")
    # h = threedtiles.build_hierarchy_from_pg(baseurl, lod_max, bbox, lod_min)
    # logger(res=True, valid=True)

def configfile(args, bbox):
    print()

    logger("Generate a configuration file for LOPoCS")
    cfg = ("flask:\n"
           "    DEBUG: True\n"
           "    LOG_LEVEL: debug\n"
           "    PG_HOST: {11}\n"
           "    PG_USER: {12}\n"
           "    PG_NAME: {0}\n"
           "    PG_PORT: {1}\n"
           "    PG_COLUMN: pa\n"
           "    PG_TABLE: {2}\n"
           "    PG_PASSWORD: {13}\n"
           "    ROOT_HCY: {14}\n"
           "    DEPTH: {3}\n"
           "    BB: [{4}, {5}, {6}, {7}, {8}, {9}]\n"
           "    USE_MORTON: True\n"
           "    CACHE_DIR: {10}\n"
           "    POTREE_SCH_PCID_SCALE_01: 2\n"
           "    POTREE_SCH_PCID_SCALE_001: 3\n"
           "    STATS: False\n"
           .format(args.pg_db, args.pg_port, args.pg_table, args.lod_max+1, bbox[0],
                   bbox[1], bbox[2], bbox[3], bbox[4], bbox[5],
                   os.path.abspath(args.lopocs_cachedir),
                   args.pg_host, args.pg_user, args.pg_pwd,
                   "potree.hcy"))
    path = os.path.join(args.outdir, 'lopocs.yml')
    f = open(path, 'w')
    f.write(cfg)
    f.close()
    logger(res=True, valid=True)

    logger("Generate a configuration file for UWSGI")
    cfg =("uwsgi:\n"
          "    virtualenv: {0}\n"
          "    master: true\n"
          "    socket: {1}:{2}\n"
          "    protocol: http\n"
          "    module: lopocs.wsgi:app\n"
          "    processes: 4\n"
          "    enable-threads: true\n"
          "    lazy-apps: true\n"
          "    need-app: true\n"
          "    catch: exceptions=true\n"
          "#    logto2: {4}\n"
          "#    log-maxsize: 10000000\n"
          "    env: LOPOCS_SETTINGS={3}/lopocs.yml\n"
          .format(args.uwsgi_venv, args.uwsgi_host, args.uwsgi_port,
                  os.path.abspath(args.outdir), args.uwsgi_log))
    path = os.path.join(args.outdir, 'lopocs.uwsgi.yml')
    f = open(path, 'w')
    f.write(cfg)
    f.close()
    logger(res=True, valid=True)

def potreeviewer(args):
    potree_dir = os.path.join(LOPOCS_MODULE_DIR, "vendor/potree")

    logger("Copy Potree project")
    copy_tree(potree_dir, os.path.join(args.outdir, "potree"))
    logger(res=True, valid=True)

    logger("Prepare Potree html file")
    src = os.path.join(potree_dir, "examples/greyhound_helens.html")
    dst = os.path.abspath(os.path.join(args.outdir, "potree/examples/potree.html"))

    replacements = {'192.168.1.12':args.uwsgi_host, '5000':str(args.uwsgi_port)}
    with open(src) as infile, open(dst, 'w') as outfile:
        for line in infile:
            for src, target in replacements.items():
                line = line.replace(src, target)
            outfile.write(line)

    os.symlink(dst, os.path.join(args.outdir, "potree.html"))

    logger(res=True, valid=True)

# -----------------------------------------------------------------------------
# main
# -----------------------------------------------------------------------------
if __name__ == '__main__':
    descr = 'Prepare database for LOPoCS'
    parser = argparse.ArgumentParser(description=descr)

    # general
    files_help = "input files. A regex can be used: 'input/*.las'"
    parser.add_argument('files', metavar='files', type=str, help=files_help)

    outdir_help = "output directory"
    parser.add_argument('outdir', metavar='outdir', type=str, help=outdir_help)

    epsg_help = "EPSG code (default: 4326)"
    parser.add_argument('-epsg', metavar='epsg', type=int, help=epsg_help,
                        default=4326)

    # flags
    conf_help = "print current configuration only"
    parser.add_argument('--confonly', help=conf_help, action="store_true")

    potreeviewer_help = "configure Potree viewer"
    parser.add_argument('--potreeviewer', help=potreeviewer_help, action="store_true")

    force_help = "remove database and output directory if they exist"
    parser.add_argument('--force', help=force_help, action="store_true")

    # postgres parameters
    pg_db_help = 'postgres database'
    parser.add_argument('pg_db', metavar='pg_db', type=str, help=pg_db_help)

    pg_user_help = 'postgres user (default: {})'.format(USER)
    parser.add_argument('-pg_user', metavar='pg_user', type=str,
                        help=pg_user_help, default=USER)

    pg_table_default = 'patchs'
    pg_table_help = 'postgres table (default: {})'.format(pg_table_default)
    parser.add_argument('-pg_table', metavar='pg_table', type=str,
                        help=pg_table_help, default=pg_table_default)

    pg_host_help = 'postgres host (default: localhost)'
    parser.add_argument('-pg_host', metavar='pg_host', type=str,
                        help=pg_host_help, default='localhost')

    pg_port_default = 5432
    pg_host_help = 'postgres port (default: {})'.format(pg_port_default)
    parser.add_argument('-pg_port', metavar='pg_port', type=str,
                        help=pg_host_help, default=pg_port_default)

    pg_pwd_help = 'postgres password (default: )'
    parser.add_argument('-pg_pwd', metavar='pg_pwd', type=str,
                        help=pg_pwd_help, default='')

    # pdal pipeline
    pdal_patchsize_help = "number of points per patch (default: 500)"
    parser.add_argument('-pdal_patchsize', metavar='size', type=int,
                        help=pdal_patchsize_help, default=500)

    pdal_reader_help = "PDAL reader to use in the pipeline (default: las)"
    parser.add_argument('-pdal_reader', metavar='reader', type=str,
                        help=pdal_reader_help, default='las')

    # morton
    morton_grid_help = "Grid size to compute the Morton Code (default: 64)"
    parser.add_argument('-morton_size', metavar='size', type=int,
                        help=morton_grid_help, default=64)

    # hierarchy
    lod_max_help = "Maximum Level Of Detail (default: 6)"
    parser.add_argument('-lod_max', metavar='lod_max', type=int,
                        help=lod_max_help, default=6)

    # lopocs
    lp_cachedir_default = os.path.join(HOME, '.cache', 'lopocs')
    lp_cachedir_help = ("LOPoCS cache directory (default: {})"
                        .format(lp_cachedir_default))
    parser.add_argument('-lopocs_cachedir', metavar='dir', type=str,
                        help=lp_cachedir_help, default=lp_cachedir_default)

    # uwsgi
    uwsgi_host_help = ("UWSGI host through which LOPoCS will be available (default: 127.0.0.1)")
    parser.add_argument('-uwsgi_host', metavar='uwsgi_host', type=str,
                        help=uwsgi_host_help, default='127.0.0.1')

    uwsgi_port_help = ("UWSGI port through which LOPoCS will be available (default: 5000)")
    parser.add_argument('-uwsgi_port', metavar='uwsgi_port', type=int,
                        help=uwsgi_port_help, default=5000)

    uwsgi_log_help = ("UWSGI logfile (default: /tmp/lopocs.log)")
    parser.add_argument('-uwsgi_log', metavar='uwsgi_log', type=str,
                        help=uwsgi_log_help, default='/tmp/lopocs.log')

    uwsgi_venv_default = os.path.join(SCRIPT_DIR, '../venv')
    uwsgi_venv_help = ("UWSGI virtualenv (default: {0})".format(uwsgi_venv_default))
    parser.add_argument('-uwsgi_venv', metavar='uwsgi_venv', type=str,
                        help=uwsgi_venv_help, default=uwsgi_venv_default)

    args = parser.parse_args()

    # print configuration
    config_summary(args)

    if (not args.confonly):
        # time
        start_time = time.time()

        header("LOPoCS check environment")
        env = checkenv(args)

        app = Flask(__name__)
        with app.app_context():
            header("LOPoCS prepare")
            files = getfiles(args)
            if args.force:
                clean(args)
            init_outdir(args)
            header("LOPoCS initialize database")
            dbcursor = initdb(args, env)
            header("LOPoCS fill database")
            pdal_pipeline(files, args, env)
            create_patch_index(args, dbcursor)
            header("LOPoCS preprocessing")
            bbox = getbbox()
            potreeschema(args, bbox, dbcursor)
            morton_code(args, dbcursor)
            hierarchy(app, args, bbox)
            configfile(args, bbox)

            if args.potreeviewer:
                header("LOPoCS configure viewer(s)")
                potreeviewer(args)

        # summary
        print()
        elapsed = time.time() - start_time
        npoints = Session.patch_size() * Session.approx_row_count()
        print("Duration: {} points processed in {} seconds with LOD {}."
              .format(npoints, elapsed, args.lod_max))
